site_name: Redes de Ordenadores
docs_dir: 'md'
site_dir: 'docs'
nav:
  - Introducción: index.md
  - Redes informáticas:
    - Redes informáticas: RedesInformaticas/redesInformaticas.md
    - Topologías: RedesInformaticas/topologias.md
  - Configuración de red:
    - Redes cableadas: ConfiguracionRed/redesCableadas.md
    - Redes no cableadas: ConfiguracionRed/redesNoCableadas.md
  - Software de red:
    - Software de red: SoftwareRed/softwareDeRed.md
    - Direcciones IP: SoftwareRed/direccionesIP.md
  - Seguridad en redes Wifi: seguridadWifi.md
  - Sobre mí: about.md

# theme: readthedocs
# theme: mkdocs
theme: material

# extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html

#plugins
plugins:
  - glightbox